[package]
name = "sift"
version = "0.3.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
hex = "0.4.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
walkdir = "2.5.0"
